<?php

/**
 * @file
 * Install, update and uninstall functions for the node view mode module.
 */

/**
 * Implements hook_install().
 */
function node_view_mode_install() {
  $node_types = \Drupal::entityTypeManager()
    ->getStorage('node_type')
    ->loadMultiple();
  foreach ($node_types as $bundle => $node_type) {
    \Drupal::configFactory()->getEditable('node_view_mode.settings')
      ->set('view_mode_' . $node_type->id(), 'full')
      ->save();
  }
}
